company_and_ticks = {
    "3M Company": "MMM",
    "American Express": "AXP",
    "Amgen": "AMGN",
    "Apple": "AAPL",
    "Boeing": "BA",
    "Caterpillar": "CAT",
    "Chevron":"CVX",
    "Cisco": "CSCO",
    "Coca-Cola": "KO",
    "Dow": "DOW",
    "Goldman Sachs": "GS",
    "Home Depot": "HD",
    "Honeywell": "HON",
    "IBM": "IBM",
    "Intel": "INTC",
    "Johnson & Johnson": "JNJ",
    "JPMorgan": "JPM",
    "McDonald": "MCD",
    "Merck": "MRK",
    "Microsoft": "MSFT",
    "Nike": "NKE",
    "Proctor & Gamble": "PG",
    "Salesforce": "CRM",
    "The Travelers Companies": "TRV",
    "UnitedHealth": "UNH",
    "Verizon": "VZ",
    "Visa": "V",
    "Walgreens Boots Alliance": "WBA",
    "Walmart": "WMT",
    "Disney": "DIS"
}

